#!/bin/bash

cp -r /home/steve/Bachelorarbeit/bachelorarbeit/crypto_libtom/essl/ /home/steve/Bachelorarbeit/embetter_ssl/
cp /home/steve/Bachelorarbeit/bachelorarbeit/crypto_libtom/test/inc/* /home/steve/Bachelorarbeit/embetter_ssl/test/inc/
cp /home/steve/Bachelorarbeit/bachelorarbeit/crypto_libtom/test/src/* /home/steve/Bachelorarbeit/embetter_ssl/test/src/
cp -r /home/steve/Bachelorarbeit/bacheloarbeit/doc_GCI/ /home/steve/Bachelorarbeit/bachelorarbeit/report/ /home/steve/Bachelorarbeit/bachelorarbeit/presentation/ /home/steve/Bachelorarbeit/swagner_doc

echo "DONE"
